{% set name = "wagtail-periodic-review" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail_periodic_review-{{ version }}.tar.gz
  sha256: 98fd73413439767466594eaeaa8c481ea45e17c437af538b286ed76f1a8c800d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - wagtail >=4.1
    - python-dateutil >=2.8,<3.0.0

test:
  imports:
    - wagtail_periodic_review
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Wagtail package for periodic page content reviews
  home: https://github.com/zerolab/wagtail-periodic-review
  dev_url: https://github.com/zerolab/wagtail-periodic-review/blob/main/CHANGELOG.md
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
