{% set name = "wagtail-periodic-review" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail_periodic_review-{{ version }}.tar.gz
  sha256: 5df67b512580f128838d5c782c74ed922234daafa478ed19ea133cdc511fc34a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=5.2
    - python-dateutil >=2.8,<3.0.0

test:
  imports:
    - wagtail_periodic_review
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A Wagtail package for periodic page content reviews
  home: https://github.com/zerolab/wagtail-periodic-review
  dev_url: https://github.com/zerolab/wagtail-periodic-review/blob/main/CHANGELOG.md
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
